server:
  port: 8080 #端口号
  
spring:
  application:
    name: cloud-order-service #服务名称
  devtools: #热部署
    restart:
      enabled: true
      additional-paths:      - src/main/java
    
eureka:
  client:
    #表示是否将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取自己的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka # 单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集君
