server:
  port: 7001
  
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称   配置路径：C:\Windows\System32\drivers\etc\hosts
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server 交互的地址，查询服务和注册服务都需要依赖这个地址      defaultZone: http://eureka7002.com:7002/eureka/
  #server:
    # 关闭自我保护机制，默认为打开
    # 自我保护模式：某一时刻某个服务不可用了，Eureka不会立刻清理，依旧会对该服务的信息进行保存
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）